server:
  port: 8080
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: ms-vehicles
          uri: lb://ms-vehicles:8090
          predicates: #mapeo de controladores, puede ser api/v1/vehicles tmb, dependerá de cómo se implemente
            - Path=/api/vehicle/**
        - id: ms-repairlist
          uri: lb://ms-repairlist:8091
          predicates:
            - Path=/api/repairlist/**