server:
  port: 8090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/msvehicle-db
    username: postgres
    password: admin
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://${EUREKA:localhost}:8761/eureka